"""add price

Revision ID: 87216a79459c
Revises: 26302e1a7068
Create Date: 2025-09-03 10:33:12.769241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87216a79459c"
down_revision: Union[str, Sequence[str], None] = "26302e1a7068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "total_price",
            sa.Integer(),
            sa.Computed(
                "(date_from - date_to) * price",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "total_price")
    # ### end Alembic commands ###
