"""new formula for total cost

Revision ID: 91ca3031d7b0
Revises: d5fde108af68
Create Date: 2025-09-07 12:05:39.275821

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91ca3031d7b0"
down_revision: Union[str, Sequence[str], None] = "d5fde108af68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем старые GENERATED колонки
    op.drop_column("bookings", "total_days")
    op.drop_column("bookings", "total_price")

    # Создаем новые с правильными формулами
    op.add_column(
        "bookings",
        sa.Column(
            "total_days",
            sa.Integer(),
            sa.Computed("date_to - date_from"),
            nullable=True,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "total_price",
            sa.Integer(),
            sa.Computed("(date_to - date_from) * price"),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем новые колонки
    op.drop_column("bookings", "total_days")
    op.drop_column("bookings", "total_price")

    # Возвращаем старые с неправильными формулами
    op.add_column(
        "bookings",
        sa.Column(
            "total_days",
            sa.Integer(),
            sa.Computed("date_from - date_to"),
            nullable=True,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "total_price",
            sa.Integer(),
            sa.Computed("(date_from - date_to) * price"),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
