"""newmapped

Revision ID: d5fde108af68
Revises: eb611e9b5669
Create Date: 2025-09-03 18:37:32.307186

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5fde108af68"
down_revision: Union[str, Sequence[str], None] = "eb611e9b5669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "hotels",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
