"""new

Revision ID: eb611e9b5669
Revises: 87216a79459c
Create Date: 2025-09-03 18:00:32.078738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb611e9b5669"
down_revision: Union[str, Sequence[str], None] = "87216a79459c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("quantity", sa.Integer(), nullable=False))
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("rooms", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("rooms", "image_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("rooms", "rooms_quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("rooms_quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column("rooms", "image_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("rooms", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("rooms", "quantity")
    # ### end Alembic commands ###
